In [20]:
import pandas as pd
import plotly.express as px

In [9]:
import requests
import pandas as pd

response = requests.get("https://data.minorplanetcenter.net/api/get-obs", json={"desigs": [r"C/2023 A3"], "output_format":["ADES_DF"]})

if response.ok:
    ades_df = pd.DataFrame(response.json()[0]['ADES_DF'])
else:
    print("Error: ", response.status_code, response.content)

In [11]:
ades_df

,Obstype,artsat,astcat,band,com,ctr,dec,decstar,delay,deltadec,...,subfrm,sys,trkid,trkmpc,trksub,trx,unctime,vel1,vel2,vel3
0,optical,None,Gaia2,G,None,NaN,2.4015734,None,None,None,...,None,None,00000HA807,CK23A030,CK23A030,None,None,None,None,None
1,optical,None,Gaia2,G,None,NaN,2.4020467,None,None,None,...,None,None,00000HA807,CK23A030,CK23A030,None,None,None,None,None
2,optical,None,Gaia2,G,None,NaN,2.9424585,None,None,None,...,None,None,00000HA808,CK23A030,CK23A030,None,None,None,None,None
3,optical,None,Gaia2,G,None,NaN,3.8243978,None,None,None,...,None,None,00000HA809,CK23A030,CK23A030,None,None,None,None,None
4,optical,None,Gaia2,G,None,NaN,3.8245438,None,None,None,...,None,None,00000HA809,CK23A030,CK23A030,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9456,optical,None,UCAC4,V,None,NaN,12.73415,None,None,None,...,None,None,0000000Hyhcc,None,None,None,None,None,None,None
9457,optical,None,UCAC4,V,None,NaN,12.52944,None,None,None,...,None,None,0000000I0GHh,None,None,None,None,None,None,None
9458,optical,None,UCAC4,V,None,NaN,12.52827,None,None,None,...,None,None,0000000I0GHh,None,None,None,None,None,None,None
9459,optical,None,Gaia3,G,None,NaN,12.46301,None,None,None,...,None,None,0000000HxSpa,None,None,None,None,None,None,None
9460,optical,None,Gaia3,G,None,NaN,12.46265,None,None,None,...,None,None,0000000HxSpa,None,None,None,None,None,None,None

In [12]:
ades_df[['obstime','mag']]

                       obstime    mag
0     2022-04-09T13:52:18.887Z  23.04
1     2022-04-09T14:08:45.332Z  23.27
2     2022-04-23T13:37:37.270Z  22.97
3     2022-05-26T10:32:51.125Z  22.65
4     2022-05-26T10:49:34.875Z  22.29
...                        ...    ...
9456  2025-11-15T09:35:33.000Z   20.7
9457  2025-11-19T09:06:02.000Z   19.9
9458  2025-11-19T09:15:15.000Z   20.1
9459  2025-11-20T18:38:15.000Z   19.7
9460  2025-11-20T18:50:21.000Z   20.3

[9461 rows x 2 columns]

In [15]:
ades_df[['mag', 'obstime']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9461 entries, 0 to 9460
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   mag      8833 non-null   object
 1   obstime  9461 non-null   object
dtypes: object(2)
memory usage: 148.0+ KB

In [16]:
ades_df.obstime

0       2022-04-09T13:52:18.887Z
1       2022-04-09T14:08:45.332Z
2       2022-04-23T13:37:37.270Z
3       2022-05-26T10:32:51.125Z
4       2022-05-26T10:49:34.875Z
                  ...
9456    2025-11-15T09:35:33.000Z
9457    2025-11-19T09:06:02.000Z
9458    2025-11-19T09:15:15.000Z
9459    2025-11-20T18:38:15.000Z
9460    2025-11-20T18:50:21.000Z
Name: obstime, Length: 9461, dtype: object

In [ ]:
ades_proceed_df = ades_df.copy()
ades_proceed_df.obstime = pd.to_datetime(ades_df.obstime, format='mixed')
ades_proceed_df.mag = pd.to_numeric(ades_df.mag)

In [22]:
fig = px.scatter(ades_proceed_df, x='obstime', y='mag', template= 'plotly_dark')
fig.update_yaxes(autorange="reversed")
fig.show()

In [26]:
response = requests.get("https://data.minorplanetcenter.net/api/get-orb", json={"desig": r"C/2023 A3"})

if response.ok:
    mpc_orb = response.json()[0]['mpc_orb']

else:
    print("Error: ", response.status_code, response.content)

mpc_orb

[{'CAR': {'coefficient_names': ['x', 'y', 'z', 'vx', 'vy', 'vz'],
   'coefficient_uncertainties': [7.50519e-07,
    6.25703e-07,
    7.47289e-07,
    1.7383e-09,
    1.64321e-09,
    1.977e-09],
   'coefficient_values': [0.80954582119549,
    -4.34351998655207,
    3.75516433916815,
    -0.00115880518427609,
    -0.00799882094112596,
    0.00607072243106745],
   'covariance': {'cov00': 5.632786629055931e-13,
    'cov01': -2.088868472990479e-13,
    'cov02': 2.746605651333956e-13,
    'cov03': 1.228712249542147e-15,
    'cov04': -8.710220381179138e-16,
    'cov05': 9.881792307851244e-16,
    'cov06': None,
    'cov07': None,
    'cov08': None,
    'cov09': None,
    'cov11': 3.915041222845804e-13,
    'cov12': -1.260837480816503e-13,
    'cov13': -6.923360443001851e-16,
    'cov14': 9.295726747555426e-16,
    'cov15': -5.857852226899766e-16,
    'cov16': None,
    'cov17': None,
    'cov18': None,
    'cov19': None,
    'cov22': 5.584406985392211e-13,
    'cov23': 8.700080941606041e-16,
    'cov24': -6.771075920612512e-16,
    'cov25': 1.406320275891042e-15,
    'cov26': None,
    'cov27': None,
    'cov28': None,
    'cov29': None,
    'cov33': 3.021680198935206e-18,
    'cov34': -2.490429664581052e-18,
    'cov35': 2.86759633251522e-18,
    'cov36': None,
    'cov37': None,
    'cov38': None,
    'cov39': None,
    'cov44': 2.700144909193738e-18,
    'cov45': -2.445054987360778e-18,
    'cov46': None,
    'cov47': None,
    'cov48': None,
    'cov49': None,
    'cov55': 3.908532446798902e-18,
    'cov56': None,
    'cov57': None,
    'cov58': None,
    'cov59': None,
    'cov66': None,
    'cov67': None,
    'cov68': None,
    'cov69': None,
    'cov77': None,
    'cov78': None,
    'cov79': None,
    'cov88': None,
    'cov89': None,
    'cov99': None},
   'eigenvalues': [1.00614e-10,
    1.61947e-10,
    3.61012e-10,
    4.84027e-07,
    5.82915e-07,
    9.69103e-07]},
  'COM': {'coefficient_names': ['q', 'e', 'i', 'node', 'argperi', 'peri_time'],
   'coefficient_uncertainties': [8.64164e-08,
    7.64454e-08,
    5.9942e-06,
    5.55315e-06,
    5.55019e-06,
    9.76075e-06],
   'coefficient_values': [0.391587171259034,
    1.000149313515217,
    139.1094427849999,
    21.5994728798835,
    308.5321203794502,
    60580.7538484504],
   'covariance': {'cov00': 7.467798556400302e-15,
    'cov01': -4.712158247754443e-15,
    'cov02': 1.007732958041462e-14,
    'cov03': 3.850871594376665e-14,
    'cov04': -3.794671111182907e-14,
    'cov05': 1.15642193829434e-13,
    'cov06': None,
    'cov07': None,
    'cov08': None,
    'cov09': None,
    'cov11': 5.843900449086008e-15,
    'cov12': -2.408856719109599e-14,
    'cov13': -3.853454091178327e-14,
    'cov14': -8.94072510388432e-14,
    'cov15': -9.041767281759787e-14,
    'cov16': None,
    'cov17': None,
    'cov18': None,
    'cov19': None,
    'cov22': 3.593045044857267e-11,
    'cov23': -1.084136437787078e-11,
    'cov24': -7.411019115301729e-12,
    'cov25': -9.46774085845909e-14,
    'cov26': None,
    'cov27': None,
    'cov28': None,
    'cov29': None,
    'cov33': 3.083747452345129e-11,
    'cov34': 2.268219275605018e-11,
    'cov35': -2.020812442408602e-12,
    'cov36': None,
    'cov37': None,
    'cov38': None,
    'cov39': None,
    'cov44': 3.08046437533402e-11,
    'cov45': 8.043356283592744e-12,
    'cov46': None,
    'cov47': None,
    'cov48': None,
    'cov49': None,
    'cov55': 9.527226801797674e-11,
    'cov56': None,
    'cov57': None,
    'cov58': None,
    'cov59': None,
    'cov66': None,
    'cov67': None,
    'cov68': None,
    'cov69': None,
    'cov77': None,
    'cov78': None,
    'cov79': None,
    'cov88': None,
    'cov89': None,
    'cov99': None},
   'eigenvalues': [3.00891e-08,
    5.49646e-08,
    9.38089e-08,
    1.06818e-07,
    1.35835e-07,
    9.76077e-06]},
  'categorization': {'object_type_int': 10,
   'object_type_str': 'Comet',
   'orbit_subtype_int': None,
   'orbit_subtype_str': '',
   'orbit_type': None,
   'orbit_type_int': 30,
   'orbit_type_str': ''},
  'designation_data': {'designation_count': 1,
   'iau_name': '',
   'name': 'Tsuchinshan-ATLAS',
   'orbfit_name': 'C/2023A3',
   'packed_primary_provisional_designation': 'CK23A030',
   'packed_secondary_provisional_designations': [],
   'permid': '',
   'unpacked_primary_provisional_designation': 'C/2023 A3',
   'unpacked_secondary_provisional_designations': []},
  'epoch_data': {'epoch': 61000.0, 'timeform': 'MJD', 'timesystem': 'TDT'},
  'magnitude_data': {'G': 0.1,
   'G1': None,
   'G12': None,
   'G2': None,
   'H': 8.376,
   'photometric_model': '????'},
  'moid_data': {'Earth': None, 'Jupiter': None, 'Mars': None, 'Venus': None},
  'non_grav_booleans': {'non_grav_coefficients': {'A1': False,
    'A2': False,
    'A3': False,
    'DT': False,
    'srp': False,
    'yarkovski': False},
   'non_grav_model': {'marsden': False,
    'srp': False,
    'yabushita': False,
    'yarkovski': False,
    'yc': False},
   'non_gravs': False},
  'orbit_fit_statistics': {'U_param': 0,
   'arc_length_sel': '2022-2025',
   'arc_length_total': '2022-2025',
   'nobs_optical': 9442,
   'nobs_optical_sel': 8555,
   'nobs_radar': 0,
   'nobs_radar_sel': 0,
   'nobs_total': 9442,
   'nobs_total_sel': 8555,
   'nopp': 0,
   'normalized_RMS': 0.86417,
   'not_normalized_RMS': None,
   'numparams': 6,
   'orbit_quality': 'good',
   'score1': 0.0,
   'score2': 0.0,
   'sig_to_noise_ratio': [11015980.961753126,
    5414990.608074413,
    862039.1684470717,
    5957404.6534846015,
    12327256.766250448,
    5551368.10484657],
   'snr_below_1': False,
   'snr_below_3': False},
  'software_data': {'fitting_datetime': '2025-12-18 22:21:44',
   'fitting_software_name': 'orbfit',
   'fitting_software_version': '1.0',
   'mpcorb_creation_datetime': '2025-12-18 22:49:22',
   'mpcorb_version': '0.4'},
  'system_data': {'EclipticObliquityArcseconds': '84381.448',
   'eph': 'DE431',
   'force_model': '????',
   'refframe': 'ICRF',
   'refsys': 'Ecliptic'}}]